CREATE TABLE parent (
  ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE child (
  ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  parent_id BIGINT UNSIGNED,

  FOREIGN KEY (parent_id) REFERENCES parent(ID)
);

INSERT INTO child (parent_id) VALUES (1);

INSERT INTO parent (ID) VALUES (1);

INSERT INTO child (parent_id) VALUES (1);

DELETE FROM parent WHERE ID = 1;
